### ISSUE TITLE
Planning to upload to Chrome and Firefox stores?

### ISSUE THREAD

**Issue by zusorio** [cryptodescriptor/old-twitch#2]
Are you planning to upload the add-on to the chrome and firefox web stores? The current install method isn't exactly user friendly.

**Comment by cryptodescriptor** [comment]
Use Stylus if you want automatic updates. It's only a 4 step install.

I would add to Firefox and Chrome stores, but chrome makes you purchase a developer license and I don't want to for such a small project.

**Comment by zusorio** [comment]
The Firefox store doesn't require a license or payment, just a Firefox account and if you would be interested I have a developer license and could upload the add-on (with permission and proper credit of course). I know Stylus and ublock are options and I as a developer would probably prefer those as well but there are a lot of people who aren't technical enough for these kinds of things.
